apiVersion: v1
kind: PersistentVolume
metadata:
  name: guac-extensions-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  hostPath:
    path: /opt/guacamole/extensions
    type: Directory
