apiVersion: v1
kind: Service
metadata:
  name: guacamole-lb
  namespace: guacamole
spec:
  type: LoadBalancer
  selector:
    app: guacamole
  ports:
    - name: http
      port: 80
      targetPort: 8080

