apiVersion: v1
kind: Service
metadata:
  name: guacamole-db
  namespace: guacamole
spec:
  clusterIP: None
  selector:
    app: guacamole-db
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP

