apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacamole
  namespace: guacamole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guacamole
  template:
    metadata:
      labels:
        app: guacamole
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: guacamole
          image: guacamole/guacamole:1.5.5
          ports:
            - containerPort: 8080  
          securityContext:
              runAsUser: 0
              runAsGroup: 0

          env:
            - name: POSTGRES_HOSTNAME
              value: guacamole-db
            - name: POSTGRES_DATABASE
              value: guacamole_db
            - name: POSTGRES_USER
              value: guacuser
            - name: POSTGRES_PASSWORD
              value: "StrongPassword123!"
            - name: GUACD_HOSTNAME
              value: guacd
            - name: GUACD_PORT
              value: "4822"       
          

